#ifndef C_LABS_ERRORS_H
#define C_LABS_ERRORS_H

#define OK 0
#define FIO_ERROR 1
#define NO_ELEMENTS_ERROR 2
#define FILE_NOT_FOUND_ERROR 3
#define NOT_CORRECT_ARGS 53
#define STRING_SIZE_ERROR 5
#define FILE_SIZE_ERROR 6

#endif //C_LABS_ERRORS_H
